services:
  db:
    image: library/mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change_me
      MYSQL_USER: wrangler
      MYSQL_PASSWORD: change_me
      MYSQL_DATABASE: wrangler
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 5

  wrangler:
    image: noah231515/receipt-wrangler:latest
    entrypoint: ./entrypoint.sh
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wrangler
      DB_PASSWORD: change_me
      DB_NAME: wrangler
      DB_ENGINE: mariadb
    volumes:
      - ./config:/app/receipt-wrangler-api/config
      - ./data:/app/receipt-wrangler-api/data
      - ./sqlite:/app/receipt-wrangler-api/sqlite
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9082:80
