services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wrangler
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: wrangler
    volumes:
      - ./pgsql:/var/lib/pgsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5

  wrangler:
    image: noah231515/receipt-wrangler:latest
    entrypoint: ./entrypoint.sh
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wrangler
      DB_PASSWORD: change_me
      DB_NAME: wrangler
      DB_ENGINE: postgresql
    volumes:
      - ./config:/app/receipt-wrangler-api/config
      - ./data:/app/receipt-wrangler-api/data
      - ./logs:/app/receipt-wrangler-api/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9082:80
