version: "3.5"
services:
  api:
    image: noah231515/receipt-wrangler-api:linux_arm64
    restart: always
    environment:
      DB_FILENAME: wrangler.sqlite
      DB_ENGINE: sqlite
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - ./config:/go/api/config
      - ./data:/go/api/data
      - ./sqlite:/go/api/sqlite

  frontend:
    image: noah231515/receipt-wrangler-desktop:linux_arm64
    restart: always
    ports:
      - 9081:80
