version: "3.5"
services:
  db:
    image: arm64v8/mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change_me
      MYSQL_USER: wrangler
      MYSQL_PASSWORD: change_me
      MYSQL_DATABASE: wrangler
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    image: noah231515/receipt-wrangler-api:linux_arm6
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wrangler
      DB_PASSWORD: change_me
      DB_NAME: wrangler
      DB_ENGINE: mariadb
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - ./config:/go/api/config
      - ./data:/go/api/data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: noah231515/receipt-wrangler-desktop:linux_arm64
    restart: always
    ports:
      - 9081:80
