services:
  wrangler:
    image: noah231515/receipt-wrangler:latest
    entrypoint: ./entrypoint.sh
    restart: always
    environment:
      DB_FILENAME: wrangler.sqlite
      DB_ENGINE: sqlite
    volumes:
      - ./config:/app/receipt-wrangler-api/config
      - ./data:/app/receipt-wrangler-api/data
      - ./sqlite:/app/receipt-wrangler-api/sqlite
      - ./logs:/app/receipt-wrangler-api/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9082:80
