version: "3.5"
services:
  api:
    image: noah231515/receipt-wrangler-api:latest
    restart: always
    environment:
      DB_FILENAME: wrangler.sqlite
      DB_ENGINE: sqlite
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - ./config:/go/api/config
      - ./data:/go/api/data
      - ./sqlite:/go/api/sqlite
      - ./logs:/go/api/logs
  proxy:
    image: noah231515/receipt-wrangler-proxy:latest
    ports:
      - 9082:80
    depends_on:
      - api
      - frontend

  frontend:
    image: noah231515/receipt-wrangler-desktop:latest
    restart: always
    ports:
      - 9081:80
