version: "3.5"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wrangler
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: wrangler
    volumes:
      - ./pgsql:/var/lib/pgsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    image: noah231515/receipt-wrangler-api:linux_x64
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wrangler
      DB_PASSWORD: change_me
      DB_NAME: wrangler
      DB_ENGINE: postgresql
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - ./config:/go/api/config
      - ./data:/go/api/data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: noah231515/receipt-wrangler-desktop:linux_x64
    restart: always
    ports:
      - 9081:80
